### ISSUE TITLE
Request for license change

### ISSUE THREAD

**Issue by IvanoAlvino** [sahabpardaz/log-throttle#1]
Hello,
I stumbled upon your project and I find it perfect for our needs: it's clean, easy to use and simply  achieves easily the goal of throttling the logs :)

We then saw that this project is GPL licensed and we would not be able to use it unfortunately as it is, so the question we would like to ask is if you would be willing to change the license to MIT or BSD.

Thank you in advance for your time, looking forward to hear back from you if this is a possibility!

Have a nice weekend!

**Comment by talebipour** [comment]
Hi,
We are happy to see that this project can be helpful for you. We changed the license to Apache 2.0 and now you can freely use it in your commercial project.
